# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
#
# Main prompt format
format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_state\
$git_status\
$git_commit\
$python\
$aws\
$terraform\
$line_break\
$time$character"""


# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = false

# User configuration
[username]
show_always = true
style_user = "red bold"
style_root = "red bold"
format = "[$user]($style) "
aliases = { "yassinebelmamoun" = "yassine" }

# Path/Directory configuration
[directory]
style = "blue bold"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "~"
read_only = " 🔒"
read_only_style = "red"
format = "in [$path]($style)[$read_only]($read_only_style) "

# Time configuration
[time]
disabled = false
format = "[$time]($style) "
style = "green bold"
time_format = "%H:%M:%S"
utc_time_offset = "+7"

# Git configuration
[git_branch]
symbol = " "
truncation_length = 20
truncation_symbol = "…"
style = "purple bold"
format = "on [$symbol$branch]($style) "

[git_commit]
tag_symbol = '  '

# Kubernetes configuration
[kubernetes]
format = 'on ☸ [$context \($namespace\)]($style) '
disabled = false
detect_extensions = []
detect_files = []
detect_folders = []
detect_env_vars = ['SHOW_KUBE']
contexts = [
  { context_pattern = ".*production.*", style = "bold yellow", symbol = "🟧 " },
  { context_pattern = ".*staging.*", style = "green", symbol = "🟩 " },
]

[aws]
symbol = " "

# Python configuration
[python]
pyenv_version_name = true
symbol = " "

[terraform]
format = 'with [🏎💨 $workspace]($style) '
